sudo: required

services:
  - docker

#specify the series of commands before our tests will run
before_install:
  - docker build -f Dockerfile.dev -t test_image .

#specify the series of commands to be executed
#Travic CI is going to be watching the output of each of these commands
#and from each command if it ever gets a return status code other than zero
#Travic is going to assume that our build failed or that our tests failed to run
script:
  - docker run -e CI=true test_image npm run test -- --watchAll=false

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "react-docker"
#  env: "ReactDocker-env"
#  bucket_name: "elasticbeanstalk-us-east-1-815477772645"
#  bucket_path: "react-docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"


